import type { SpotExecutionCapabilities, SpotVenue } from "./model.js";

const docs = {
  binance: ["https://developers.binance.com/docs/binance-spot-api-docs/rest-api/trading-endpoints",
    "https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api"],
  coinbase: ["https://docs.cdp.coinbase.com/api-reference/advanced-trade-api/rest-api/orders/create-order",
    "https://docs.cdp.coinbase.com/coinbase-app/advanced-trade-apis/sandbox"],
  bybit: ["https://bybit-exchange.github.io/docs/v5/order/create-order",
    "https://bybit-exchange.github.io/docs/v5/demo"],
  okx: ["https://www.okx.com/docs-v5/en/#order-book-trading-trade-post-place-order",
    "https://www.okx.com/docs-v5/en/#overview-demo-trading-services"],
  kraken: ["https://docs.kraken.com/api/docs/rest-api/add-order",
    "https://docs.kraken.com/api/docs/guides/spot-rest-auth"],
  kucoin: ["https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-order",
    "https://www.kucoin.com/docs-new/authentication"],
  gateio: ["https://www.gate.com/docs/developers/apiv4/en/#create-an-order",
    "https://www.gate.com/docs/developers/apiv4/en/#authentication",
    "https://github.com/gateio/gateapi-nodejs/blob/master/docs/SpotApi.md"],
  robinhood: ["https://docs.robinhood.com/crypto/trading/",
    "https://docs.robinhood.com/crypto/trading/#api-credentials"],
  hyperliquid: ["https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint",
    "https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#place-an-order"],
} as const;

const shared = {
  assetClass: "crypto_spot" as const,
  externalHandshake: "UNVERIFIED_DISABLED" as const,
};

export const SPOT_CAPABILITIES: Record<SpotVenue, SpotExecutionCapabilities> = {
  binance: { ...shared, venue: "binance", environments: ["paper", "testnet"],
    orderTypes: ["MARKET", "LIMIT", "LIMIT_MAKER"], timeInForce: ["GTC", "IOC", "FOK"],
    quoteMarketBuy: true, clientOrderId: { maxLength: 36, pattern: "^[A-Za-z0-9._-]+$" },
    cancelReplace: "atomic", accountIdentity: "API-key account", precisionSource: "exchangeInfo filters",
    feeSource: "myTrades commission", officialDocs: docs.binance },
  coinbase: { ...shared, venue: "coinbase", environments: ["paper"],
    orderTypes: ["MARKET", "LIMIT"], timeInForce: ["GTC", "POST_ONLY"],
    quoteMarketBuy: true, clientOrderId: { maxLength: 36, pattern: "^[A-Za-z0-9-]+$" },
    cancelReplace: "cancel_then_new", accountIdentity: "retail portfolio UUID",
    precisionSource: "product base/quote increments", feeSource: "order total_fees",
    officialDocs: docs.coinbase },
  bybit: { ...shared, venue: "bybit", environments: ["paper", "testnet", "demo"],
    orderTypes: ["MARKET", "LIMIT"], timeInForce: ["GTC", "IOC", "FOK", "POST_ONLY"],
    quoteMarketBuy: true, clientOrderId: { maxLength: 36, pattern: "^[A-Za-z0-9_-]+$" },
    cancelReplace: "cancel_then_new", accountIdentity: "unified trading account",
    precisionSource: "instruments-info lotSizeFilter/priceFilter", feeSource: "execution fee",
    officialDocs: docs.bybit },
  okx: { ...shared, venue: "okx", environments: ["paper", "demo"],
    orderTypes: ["MARKET", "LIMIT"], timeInForce: ["GTC", "IOC", "FOK", "POST_ONLY"],
    quoteMarketBuy: true, clientOrderId: { maxLength: 32, pattern: "^[A-Za-z0-9]+$" },
    cancelReplace: "atomic", accountIdentity: "account plus sub-account",
    precisionSource: "public instruments lotSz/minSz/tickSz", feeSource: "fills fee/feeCcy",
    officialDocs: docs.okx },
  kraken: { ...shared, venue: "kraken", environments: ["paper"],
    orderTypes: ["MARKET", "LIMIT"], timeInForce: ["GTC", "IOC", "POST_ONLY"],
    quoteMarketBuy: false, clientOrderId: { maxLength: 36, pattern: "^[0-9a-fA-F-]{32,36}$" },
    cancelReplace: "atomic", accountIdentity: "API-key account",
    precisionSource: "AssetPairs ordermin/lot_decimals/pair_decimals", feeSource: "trade fee",
    officialDocs: docs.kraken },
  kucoin: { ...shared, venue: "kucoin", environments: ["paper"],
    orderTypes: ["MARKET", "LIMIT"], timeInForce: ["GTC", "IOC", "FOK", "POST_ONLY"],
    quoteMarketBuy: true, clientOrderId: { maxLength: 40, pattern: "^[A-Za-z0-9_-]+$" },
    cancelReplace: "cancel_then_new", accountIdentity: "trade account plus API key",
    precisionSource: "symbols baseIncrement/priceIncrement/minFunds", feeSource: "fills fee/feeCurrency",
    officialDocs: docs.kucoin },
  gateio: { ...shared, venue: "gateio", environments: ["paper"],
    orderTypes: ["MARKET", "LIMIT", "LIMIT_MAKER"], timeInForce: ["GTC", "IOC", "FOK", "POST_ONLY"],
    quoteMarketBuy: true, clientOrderId: { maxLength: 28, pattern: "^t-[A-Za-z0-9_.-]+$", transformedPrefix: "t-" },
    cancelReplace: "cancel_then_new", accountIdentity: "API-key account",
    precisionSource: "currency_pairs amount_precision/precision/min_quote_amount", feeSource: "order fee/fee_currency",
    officialDocs: docs.gateio },
  robinhood: { ...shared, venue: "robinhood", environments: ["paper"],
    orderTypes: ["MARKET", "LIMIT"], timeInForce: ["GTC"],
    quoteMarketBuy: false, clientOrderId: { maxLength: 36, pattern: "^[0-9a-fA-F-]{36}$" },
    cancelReplace: "cancel_then_new", accountIdentity: "Robinhood Crypto account",
    precisionSource: "trading pair asset increments", feeSource: "executions effective_price/spread",
    officialDocs: docs.robinhood },
  hyperliquid: { ...shared, venue: "hyperliquid", environments: ["paper", "testnet"],
    orderTypes: ["LIMIT"], timeInForce: ["GTC", "IOC", "POST_ONLY"], quoteMarketBuy: false,
    clientOrderId: { maxLength: 34, pattern: "^0x[0-9a-fA-F]{32}$" },
    cancelReplace: "cancel_then_new", accountIdentity: "wallet/subaccount address",
    precisionSource: "spotMeta szDecimals plus significant-figure price rules", feeSource: "userFills fee/feeToken",
    officialDocs: docs.hyperliquid },
};

export function spotCapabilities(): SpotExecutionCapabilities[] {
  return Object.values(SPOT_CAPABILITIES);
}
