CREATE TABLE "DerivativeExecutionOrder" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "platformIntentId" TEXT NOT NULL,
  "platformDedupeKey" TEXT NOT NULL,
  "platformPayloadHash" TEXT NOT NULL,
  "platformIntentCreatedAt" DATETIME NOT NULL,
  "exchangeAccountId" TEXT NOT NULL,
  "venue" TEXT NOT NULL,
  "environment" TEXT NOT NULL,
  "canonicalInstrumentId" TEXT NOT NULL,
  "venueSymbol" TEXT NOT NULL,
  "contractKind" TEXT NOT NULL,
  "contractSize" TEXT NOT NULL,
  "baseCurrency" TEXT NOT NULL,
  "quoteCurrency" TEXT NOT NULL,
  "settlementCurrency" TEXT NOT NULL,
  "marginCurrency" TEXT NOT NULL,
  "expiry" DATETIME,
  "positionDirection" TEXT NOT NULL,
  "actionSide" TEXT NOT NULL,
  "quantityUnit" TEXT NOT NULL,
  "requestedQuantity" TEXT,
  "marginMode" TEXT NOT NULL,
  "leverage" TEXT,
  "positionMode" TEXT NOT NULL,
  "reduceOnly" BOOLEAN NOT NULL DEFAULT false,
  "closePosition" BOOLEAN NOT NULL DEFAULT false,
  "orderType" TEXT NOT NULL,
  "timeInForce" TEXT,
  "limitPrice" TEXT,
  "triggerPrice" TEXT,
  "triggerPriceRole" TEXT,
  "protectionKind" TEXT,
  "paperReferencePrice" TEXT,
  "positionSnapshot" TEXT,
  "shariahContext" TEXT,
  "clientOrderId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'requested',
  "providerOrderId" TEXT,
  "providerStatus" TEXT,
  "filledContracts" TEXT NOT NULL DEFAULT '0',
  "filledBaseQty" TEXT NOT NULL DEFAULT '0',
  "filledNotional" TEXT NOT NULL DEFAULT '0',
  "averageFillPrice" TEXT,
  "realizedPnl" TEXT NOT NULL DEFAULT '0',
  "unrealizedPnl" TEXT NOT NULL DEFAULT '0',
  "pnlCurrency" TEXT,
  "fundingAmount" TEXT NOT NULL DEFAULT '0',
  "fundingCurrency" TEXT,
  "feeAmount" TEXT,
  "feeCurrency" TEXT,
  "markPrice" TEXT,
  "indexPrice" TEXT,
  "lastPrice" TEXT,
  "liquidationPrice" TEXT,
  "maintenanceMargin" TEXT,
  "error" TEXT,
  "submittedAt" DATETIME,
  "acknowledgedAt" DATETIME,
  "lastFillAt" DATETIME,
  "reconciledAt" DATETIME,
  "completedAt" DATETIME,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "DerivativeExecutionOrder_exchangeAccountId_fkey"
    FOREIGN KEY ("exchangeAccountId") REFERENCES "ExchangeAccount" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "DerivativeExecutionOrder_platformIntentId_key" ON "DerivativeExecutionOrder"("platformIntentId");
CREATE UNIQUE INDEX "DerivativeExecutionOrder_platformDedupeKey_key" ON "DerivativeExecutionOrder"("platformDedupeKey");
CREATE UNIQUE INDEX "DerivativeExecutionOrder_clientOrderId_key" ON "DerivativeExecutionOrder"("clientOrderId");
CREATE INDEX "DerivativeExecutionOrder_status_createdAt_idx" ON "DerivativeExecutionOrder"("status", "createdAt");
CREATE INDEX "DerivativeExecutionOrder_exchangeAccountId_venueSymbol_createdAt_idx"
  ON "DerivativeExecutionOrder"("exchangeAccountId", "venueSymbol", "createdAt");
