import type { DerivativeExecutionCapabilities, DerivativeVenue } from "./model.js";

const docs = {
  binance: ["https://developers.binance.com/docs/derivatives/usds-margined-futures/trade/rest-api/New-Order",
    "https://developers.binance.com/docs/derivatives/quick-start"],
  bybit: ["https://bybit-exchange.github.io/docs/v5/order/create-order",
    "https://bybit-exchange.github.io/docs/v5/demo"],
  okx: ["https://www.okx.com/docs-v5/en/#order-book-trading-trade-post-place-order",
    "https://www.okx.com/docs-v5/en/#overview-demo-trading-services"],
  kucoin: ["https://www.kucoin.com/docs-new/rest/futures-trading/orders/add-order",
    "https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-symbol"],
  gateio: ["https://www.gate.com/docs/developers/apiv4/en/#create-a-futures-order",
    "https://www.gate.com/docs/developers/futures/",
    "https://github.com/gateio/gateapi-nodejs/blob/master/docs/FuturesApi.md",
    "https://github.com/gateio/gateapi-nodejs/blob/master/docs/DeliveryApi.md"],
  kraken: ["https://docs.kraken.com/api/docs/futures-api/trading/send-order",
    "https://docs.kraken.com/api/docs/guides/futures-introduction/"],
  hyperliquid: ["https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint",
    "https://hyperliquid.gitbook.io/hyperliquid-docs/trading/order-types"],
  coinbase: ["https://docs.cdp.coinbase.com/api-reference/international-exchange-api/rest-api/orders/create-order",
    "https://docs.cdp.coinbase.com/international-exchange/introduction/sandbox",
    "https://docs.cdp.coinbase.com/international-exchange/concepts/instruments"],
} as const;

const exposure = "Paper protection observes completed candles only, then submits at the next market observation; process/network downtime leaves the position unprotected and trigger-price parity is not claimed.";
const shared = {
  assetClass: "crypto_derivative" as const,
  orderTypes: ["MARKET", "LIMIT", "STOP_MARKET", "TAKE_PROFIT_MARKET"] as const,
  timeInForce: ["GTC", "IOC", "FOK", "POST_ONLY"] as const,
  marginModes: ["ISOLATED", "CROSS"] as const,
  markPrice: true, indexPrice: true, lastPrice: true, funding: true,
  externalHandshake: "UNVERIFIED_DISABLED" as const,
};

export const DERIVATIVE_CAPABILITIES: Record<DerivativeVenue, DerivativeExecutionCapabilities> = {
  binance: { ...shared, venue: "binance", environments: ["paper", "testnet"],
    contractKinds: ["LINEAR", "INVERSE"], quantityUnits: ["CONTRACTS", "BASE"],
    positionModes: ["ONE_WAY", "HEDGE"], leverage: { atOrder: false, maximum: "125", source: "symbol leverage brackets; leverage is a separate account mutation" },
    reduceOnly: true, closePosition: true, datedExpiry: true,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK", "LAST"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 36, pattern: "^[A-Za-z0-9._:-]+$" }, officialDocs: docs.binance,
    notes: ["closePosition is native only for conditional market close orders", "reduceOnly is incompatible with hedge-mode positionSide orders"] },
  bybit: { ...shared, venue: "bybit", environments: ["paper", "testnet", "demo"],
    contractKinds: ["LINEAR", "INVERSE"], quantityUnits: ["CONTRACTS", "BASE"],
    positionModes: ["ONE_WAY", "HEDGE"], leverage: { atOrder: false, maximum: null, source: "instrument leverageFilter; leverage is configured separately" },
    reduceOnly: true, closePosition: true, datedExpiry: true,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK", "INDEX", "LAST"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 36, pattern: "^[A-Za-z0-9_-]+$" }, officialDocs: docs.bybit,
    notes: ["positionIdx carries one-way/hedge leg", "zero-quantity reduce-only close is venue-specific and never synthesized by the canonical layer"] },
  okx: { ...shared, venue: "okx", environments: ["paper", "demo"],
    contractKinds: ["LINEAR", "INVERSE"], quantityUnits: ["CONTRACTS"],
    positionModes: ["ONE_WAY", "HEDGE"], leverage: { atOrder: false, maximum: null, source: "account leverage-info; leverage is configured separately" },
    reduceOnly: true, closePosition: false, datedExpiry: true,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK", "INDEX", "LAST"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 32, pattern: "^[A-Za-z0-9]+$" }, officialDocs: docs.okx,
    notes: ["sz is contracts", "close-position requests are rejected rather than translated"] },
  kucoin: { ...shared, venue: "kucoin", environments: ["paper"],
    contractKinds: ["LINEAR", "INVERSE"], quantityUnits: ["CONTRACTS"],
    positionModes: ["ONE_WAY"], leverage: { atOrder: true, maximum: null, source: "symbol multiplier/maxLeverage" },
    reduceOnly: true, closePosition: true, datedExpiry: true,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK", "INDEX", "LAST"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 40, pattern: "^[A-Za-z0-9_-]+$" }, externalHandshake: "NOT_AVAILABLE",
    officialDocs: docs.kucoin, notes: ["No current official non-production futures order handshake was established; fixture/paper only"] },
  gateio: { ...shared, venue: "gateio", environments: ["paper", "testnet"],
    contractKinds: ["LINEAR", "INVERSE"], quantityUnits: ["CONTRACTS"],
    positionModes: ["ONE_WAY", "HEDGE"], leverage: { atOrder: false, maximum: null, source: "contract order_size_max and position leverage endpoint" },
    reduceOnly: true, closePosition: true, datedExpiry: true,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK", "INDEX", "LAST"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 30, pattern: "^t-[A-Za-z0-9_.-]+$" }, officialDocs: docs.gateio,
    notes: ["size is signed contracts at the venue; canonical actionSide is mapped in the adapter"] },
  kraken: { ...shared, venue: "kraken", environments: ["paper", "demo"],
    contractKinds: ["LINEAR", "INVERSE"], quantityUnits: ["CONTRACTS", "BASE"],
    positionModes: ["ONE_WAY"], leverage: { atOrder: false, maximum: null, source: "instrument margin schedule" },
    reduceOnly: true, closePosition: false, datedExpiry: true,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK", "INDEX", "LAST"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 36, pattern: "^[0-9a-f-]{36}$" }, officialDocs: docs.kraken,
    notes: ["demo-futures is the only modeled external environment", "close-position requests are rejected rather than translated"] },
  hyperliquid: { ...shared, venue: "hyperliquid", environments: ["paper", "testnet"],
    contractKinds: ["LINEAR"], quantityUnits: ["BASE"], positionModes: ["ONE_WAY"],
    orderTypes: ["LIMIT", "STOP_MARKET", "TAKE_PROFIT_MARKET"],
    leverage: { atOrder: false, maximum: null, source: "per-asset margin table and updateLeverage action" },
    reduceOnly: true, closePosition: false, datedExpiry: false,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: ["STOP_MARKET", "TAKE_PROFIT_MARKET"],
      nativeTriggerRoles: ["MARK"], nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 34, pattern: "^0x[0-9a-f]{32}$" }, officialDocs: docs.hyperliquid,
    notes: ["EIP-712 mutation signing remains an official-SDK integration boundary", "no dated delivery products"] },
  coinbase: { ...shared, venue: "coinbase", environments: ["paper", "testnet"],
    contractKinds: ["LINEAR"], quantityUnits: ["BASE"], positionModes: ["ONE_WAY"],
    leverage: { atOrder: false, maximum: null, source: "International Exchange instrument/account limits" },
    reduceOnly: true, closePosition: false, datedExpiry: false,
    protective: { paper: "COMPLETED_CANDLE_MARKET_AFTER_CLOSE", nativeOrderTypes: [], nativeTriggerRoles: [],
      nativeRestingProof: "UNVERIFIED_DISABLED", exposure },
    clientOrderId: { maxLength: 36, pattern: "^[0-9a-f-]{36}$" },
    officialDocs: docs.coinbase,
    notes: ["testnet denotes the official International Exchange n5e1 sandbox; no handshake is claimed", "sandbox onboarding is account-team/entitlement dependent"] },
};

export function derivativeCapabilities(): DerivativeExecutionCapabilities[] {
  return Object.values(DERIVATIVE_CAPABILITIES);
}
